#include "media/decode_progress.h"
#pragma once
#include "settings_value.h"
#include "media/video_state.h"
#include "review_window.h"
#include "translator.h"
#include "file_resources.h"
#include "media/caption_session.h"
#include "detection/detection_methods.h"
#include "detection_blocks.h"
#include "detector_records.h"
#include "interval_storage.h"
#include "portable_threads.h"
#include <memory>
#include <array>
#include <optional>
#include <span>
#include <vector>

struct RecordingState {
    comskip::media::DecodeProgress decode_progress;
    unsigned char XDSbuffer[40][100]{};
    int lastXDS= 0;
    int firstXDS= 1;
    int startXDS= 1;
    int baseXDS= 0;
    std::array<std::array<int, 256>, 4> own_histogram{};
    int scan_step{};
    int beforeblocks[100]{};
    int afterblocks[100]{};
    std::vector<int> length_order;
    bool length_sorted = false;
    int min_val[10]{};
    int max_val[10]{};
    int delta_val[10]{};
    std::vector<std::string> argument;
    bool initialized= false;
    const char * progname= "ComSkip";
    comskip::platform::FilePtr out_file;
    comskip::platform::FilePtr incommercial_file;
    comskip::platform::FilePtr ini_file;
    comskip::platform::FilePtr edl_file;
    comskip::platform::FilePtr live_file;
    comskip::platform::FilePtr edlp_file;
    comskip::platform::FilePtr log_file;
    comskip::platform::FilePtr tuning_file;
    comskip::platform::FilePtr training_file;
    comskip::platform::FilePtr aspect_file;
    int audio_channels{};
    comskip::platform::FilePtr in_file;
    int debug_cur_segment{};
    std::vector<frame_info> frame;
    long frame_count{};
    long max_frame_count{};
    std::vector<schange_info> schange;
    long schange_count= 0;
    long max_schange_count= 0;
    long black_count= 0;
    std::vector<black_frame_info> black;
    long max_black_count{};
    std::vector<block_info> cblock{comskip::detection::empty_block()};
    long block_count= 0;
    std::vector<logo_block_info> logo_block;
    long logo_block_count= 0;
    long max_logo_block_count{};
    bool processCC{};
    ccPacket lastcc{};
    ccPacket cc{};
    std::vector<cc_block_info> cc_block;
    long cc_block_count= 0;
    long max_cc_block_count{};
    int last_cc_type = comskip::detection::caption_type_value(comskip::detection::CaptionType::none);
    int current_cc_type = comskip::detection::caption_type_value(comskip::detection::CaptionType::none);
    bool cc_on_screen= false;
    bool cc_in_memory= false;
    std::vector<XDS_block_info> XDS_block;
    long XDS_block_count= 0;
    long max_XDS_block_count{};
    std::vector<cc_text_info> cc_text;
    long cc_text_count= 0;
    long max_cc_text_count= 0;
    std::vector<ar_block_info> ar_block;
    long ar_block_count= 0;
    long max_ar_block_count{};
    int last_audio_channels= 2;
    double last_ar_ratio= 0.0;
    double ar_ratio_trend= 0.0;
    int ar_ratio_trend_counter= 0;
    int ar_ratio_start= 0;
    int ar_misratio_trend_counter= 0;
    int ar_misratio_start= 0;
    std::vector<ac_block_info> ac_block;
    long ac_block_count= 0;
    long max_ac_block_count{};
    int commercial_count= -1;
    std::vector<Legacy_commercial_entry> commercial;
    int reffer_count= -1;
    std::vector<Legacy_reffer_entry> reffer;
    std::array<Legacy_ar_histogram_entry, 1000> ar_histogram{};
    double dominant_ar{};
    std::array<Legacy_ac_histogram_entry, 12> ac_histogram{};
    int dominant_ac{};
    int use_cuvid{};
    int use_vdpau{};
    int use_dxva2{};
    int use_qsv{};
    int dvrms_live_tv_retries{};
    int standoff{};
    int dvrmsstandoff= 120000;
    std::string logofilename;
    std::string logfilename;
    std::string mpegfilename;
    std::string exefilename;
    std::string inbasename;
    std::string workbasename;
    std::string outbasename;
    std::string shortbasename;
    std::string inifilename;
    std::string dictfilename;
    std::string out_filename;
    std::string incommercial_filename;
    std::string outputdirname;
    std::string filename;
    int curvolume= -1;
    int ascr{};
    int scr{};
    int framenum_real{};
    int frames_with_logo{};
    int framesprocessed= 0;
    std::string HomeDir;
    double average_score{};
    int brightness= 0;
    long sum_brightness=0;
    long sum_count{};
    int uniformHistogram[256]{};
    int brightHistogram[256]{};
    int blackHistogram[256]{};
    int volumeHistogram[256]{};
    int silenceHistogram[256]{};
    int logoHistogram[256]{};
    int volumeScale= 10;
    int last_brightness= 0;
    int min_brightness_found{};
    int min_volume_found{};
    int max_logo_gap{};
    int max_nonlogo_block_length{};
    double logo_overshoot{};
    double logo_quality{};
    int width{};
    int old_width{};
    int videowidth{};
    int height{};
    int old_height{};
    int ar_width= 0;
    int subsample_video= 0x1ff;
    std::vector<char> haslogo;
    int pixel_width{};
    int pixel_height{};
    int pixel_video_width{};
    int review_source_width{};
    int review_source_height{};
    void ensure_pixel_buffers(bool use_logo);
    void ensure_review_graph(int width, int height);
    int selftest{};
    double avg_fps= 22;
    int min_hasBright= 255000;
    int min_dimCount= 255000;
    int validate_ar= true;
    int min_volume=0;
    int min_uniform= 0;
    std::string ini_text{};
    bool play_nice= false;
    int after_start= 0;
    int before_end= 0;
    int doublCheckLogoCount= 0;
    bool output_console{};
    bool framearray= true;
    bool only_strict= false;
    int schange_threshold= 90;
    int schange_cutlevel= 15;
    double ar_rounding= 100;
    long avg_brightness= 0;
    long maxi_volume= 0;
    long avg_volume= 0;
    long avg_silence= 0;
    long avg_uniform= 0;
    double avg_schange= 0.0;
    double dictionary_modifier= 1.05;
    bool detectBlackFrames{};
    bool detectSceneChanges{};
    // Borrowed pixels for the currently submitted decoded frame. The span is
    // empty between frames and carries the validated image extent.
    std::span<unsigned char> frame_ptr{};
    bool sceneHasChanged{};
    int sceneChangePercent{};
    bool lastFrameWasBlack= false;
    int lastFrameWasSceneChange{};
    std::array<long, 256> histogram{};
    std::array<long, 256> lastHistogram{};
    int cutscenematch{};
    int cutscenes=0;
    unsigned char cutscene[8][120000]{};
    int csbrightness[8]{};
    int cslength[8]{};
    bool logoInfoAvailable{};
    bool secondLogoSearch= false;
    bool logoBuffersFull= false;
    int logoTrendCounter= 0;
    double logoFreq= 1.0;
    bool lastLogoTest= false;
    std::vector<int> logoFrameNum;
    int oldestLogoBuffer{};
    bool curLogoTest= false;
    int minHitsForTrend= 10;
    double logoPercentage= 0.0;
    bool reverseLogoLogic= false;
    std::vector<unsigned char> horiz_count;
    std::vector<unsigned char> vert_count;
    double borderIgnore= .05;
    int int_edge_radius= 2;
    int edge_count= 0;
    int hedge_count= 0;
    int vedge_count= 0;
    std::optional<int> newestLogoBuffer;
    std::vector<std::vector<unsigned char>> logoFrameBuffer;
    int logoFrameBufferSize= 0;
    int lwidth{};
    int lheight{};
    int tlogoMinX{};
    int tlogoMaxX{};
    int tlogoMinY{};
    int tlogoMaxY{};
    int edgemask_filled=0;
    std::vector<unsigned char> thoriz_edgemask;
    std::vector<unsigned char> tvert_edgemask;
    int clogoMinX{};
    int clogoMaxX{};
    int clogoMinY{};
    int clogoMaxY{};
    std::vector<unsigned char> choriz_edgemask;
    std::vector<unsigned char> cvert_edgemask;
    comskip::platform::FilePtr dump_data_file;
    uint8_t ccData[500]{};
    int ccDataLen{};
    uint8_t prevccData[500]{};
    int prevccDataLen{};
    long cc_count[5]= { 0, 0, 0, 0, 0 };
    int most_cc_type = comskip::detection::caption_type_value(comskip::detection::CaptionType::none);
    std::array<std::array<unsigned char, 32>, 15> cc_screen{};
    std::array<std::array<unsigned char, 32>, 15> cc_memory{};
    int minY{};
    int maxY{};
    int minX{};
    int maxX{};
    bool isSecondPass= false;
    long lastFrame= 0;
    long lastFrameCommCalculated{};
    bool loadingCSV= false;
    bool loadingTXT= false;
    int helpflag= 0;
    int timeflag= 0;
    int recalculate=0;
    double currentGoodEdge= 0.0;
    std::array<int, 4800> lineStart{};
    std::array<int, 4800> lineEnd{};
    std::vector<unsigned char> hor_edgecount;
    std::vector<unsigned char> ver_edgecount;
    std::vector<unsigned char> max_br;
    std::vector<unsigned char> min_br;
    std::vector<unsigned char> graph;
    int gy=0;
    int pass= 0;
    double test_pts= 0.0;
    int av_log_level=AV_LOG_INFO;
    comskip::media::DictionaryPtr myoptions{};
    std::unique_ptr<VideoState> video_owner{};
    int64_t pev_best_effort_timestamp= 0;
    int have_frame_rate{};
    int stream_index{};
    int64_t best_effort_timestamp{};
    int coding_type{};
    comskip::platform::FilePtr timing_file;
    int is_AC3{};
    int AC3_rate{};
    int AC3_mode{};
    int is_h264=0;
    int is_AAC=0;
    unsigned int AC3_sampling_rate{};
    int AC3_byterate{};
    int demux_pid=0;
    int demux_asf=0;
    int last_pid{};
    int pids[100]{};
    int pid_type[100]{};
    int pid_pcr[100]{};
    int pid_pid[100]{};
    int top_pid_count[8192]{};
    int top_pid_pid{};
    int pid{};
    int selected_video_pid=0;
    int selected_audio_pid=0;
    int selected_subtitle_pid=0;
    int selection_restart_count= 0;
    int found_pids=0;
    int64_t pts{};
    double initial_pts= 0.0;
    int64_t final_pts{};
    double pts_offset= 0.0;
    int initial_pts_set= 0;
    double initial_apts{};
    double apts_offset= 0.0;
    int initial_apts_set= 0;
    int do_audio_repair= 1;
    int muxrate{};
    int byterate=10000;
    int soft_seeking=0;
    char pict_type{};
    int sigint= 0;
    int decoder_verbose= 0;
    double selftest_target= 0.0;
    int framenum{};
    fpos_t filepos{};
    int64_t goppos{};
    int64_t infopos{};
    int64_t packpos{};
    int64_t ptspos{};
    int64_t headerpos{};
    int64_t frompos{};
    int64_t SeekPos{};
    int variable_bitrate{};
    int max_internal_repair_size= 40;
    int reviewing= 0;
    int count=0;
    int currentSecond=0;
    int reorderCC= 0;
    int csRestart{};
    int csStartJump{};
    int csStepping{};
    int csJumping{};
    int csFound{};
    int seekIter= 0;
    int seekDirection= 0;
    int retries{};
    double base_apts= 0.0;
    double apts{};
    double top_apts= 0.0;
    std::array<short, 1600000> audio_buffer{};
    std::size_t audio_buffer_size{};
    int audio_samples= 0;
    int sound_frame_counter= 0;
    int max_volume_found= 0;
    int tracks_without_sound= 0;
    int frames_without_sound= 0;
    int frames_with_loud_sound= 0;
    std::array<uint8_t, 100000> ac3_packet{};
    int ac3_packet_index= 0;
    int data_size{};
    int ac3_package_misalignment_count= 0;
    unsigned char MPEG2SysHdr[24]= {0x00, 0x00, 0x01, 0xBB, 00, 0x12, 0x80, 0x8E, 0xD3, 0x04, 0xE1, 0x7F, 0xB9, 0xE0, 0xE0, 0xB8, 0xC0, 0x54, 0xBD, 0xE0, 0x3A, 0xBF, 0xE0, 0x02};
    comskip::platform::FilePtr dump_audio_file;
    comskip::platform::FilePtr dump_video_file;
    int oheight= 0;
    int owidth= 0;
    double divider= 1;
    std::optional<int> oldfrm;
    int zstart= 0;
    int zfactor= 1;
    int show_XDS=0;
    int show_silence=0;
    int preMarkerFrame= 0;
    int postMarkerFrame= 0;
    char CauseString_cs[4][80]{};
    int CauseString_ii=0;
    unsigned char AddXDS_XDSbuf[1024]{};
    int AddXDS_c= 0;
    int DetectCredits_credit_length= 0;
    int DetectCredits_prev_credit_length= 0;
    int DetectCredits_prev_credit_end= 0;
    int DetectCredits_credit_count= 0;
    int sound_to_frames_old_c= 0;
    double sound_to_frames_old_audio_clock=0.0;
    int sound_to_frames_old_sample_rate= 0;
    int video_packet_process_find_29fps= 0;
    int video_packet_process_force_29fps= 0;
    int video_packet_process_find_25fps= 0;
    int video_packet_process_force_25fps= 0;
    int video_packet_process_find_24fps= 0;
    int video_packet_process_force_24fps= 0;
    double video_packet_process_prev_pts= 0.0;
    double video_packet_process_prev_real_pts= 0.0;
    double video_packet_process_prev_strange_step= 0.0;
    int video_packet_process_prev_strange_framenum= 0;
    int log_callback_report_print_prefix= 1;
    std::unique_ptr<ScanWorkers> scan_workers;
};

// Own one context per analysis. Functions borrow it explicitly; there is no
// process-wide current-context pointer or thread-local replacement.
struct RecordingContext {
    comskip::config::Settings settings = comskip::config::default_settings();
    RecordingState state;
    comskip::ui::ReviewWindow window;
    comskip::localization::Translator translator;
    std::unique_ptr<comskip::media::CaptionSession> captions;
};
