#include "settings.h"
#include "profile.h"
#include <cstring>
#include <functional>
#include <vector>
using comskip::config::defaults;
bool ALIGN_AC3_PACKETS = defaults().number<bool>("align_ac3_packets");

int commDetectMethod = defaults().number<int>("detect_method");
int verbose = defaults().number<int>("verbose");
int max_brightness = defaults().number<int>("max_brightness");
int maxbright = defaults().number<int>("maxbright");
int test_brightness = defaults().number<int>("test_brightness");
int max_avg_brightness = defaults().number<int>("max_avg_brightness");
double max_commercialbreak = defaults().number<double>("max_commercialbreak");
double min_commercialbreak = defaults().number<double>("min_commercialbreak");
double max_commercial_size = defaults().number<double>("max_commercial_size");
double min_commercial_size = defaults().number<double>("min_commercial_size");
double min_show_segment_length = defaults().number<double>("min_show_segment_length");
int max_volume = defaults().number<int>("max_volume");
int max_silence = defaults().number<int>("max_silence");
int non_uniformity = defaults().number<int>("non_uniformity");
int min_silence = defaults().number<int>("min_silence");
int remove_silent_segments = defaults().number<int>("remove_silent_segments");
int noise_level = defaults().number<int>("noise_level");
int brightness_jump = defaults().number<int>("brightness_jump");
double fps = defaults().number<double>("fps");
int validate_silence = defaults().number<int>("validate_silence");
int validate_uniform = defaults().number<int>("validate_uniform");
int validate_scenechange = defaults().number<int>("validate_scenechange");
double global_threshold = defaults().number<double>("global_threshold");
int disable_heuristics = defaults().number<int>("disable_heuristics");
int cut_on_ac_change = defaults().number<int>("cut_on_ac_change");
int thread_count = defaults().number<int>("thread_count");
int hardware_decode = defaults().number<int>("hardware_decode");
int play_nice_start = defaults().number<int>("play_nice_start");
int play_nice_end = defaults().number<int>("play_nice_end");
long play_nice_sleep = defaults().number<long>("play_nice_sleep");
int max_repair_size = defaults().number<int>("max_repair_size");
int ms_audio_delay = -defaults().number<int>("ms_audio_delay");
int volume_slip = defaults().number<int>("volume_slip");
int lowres = defaults().number<int>("lowres");
int skip_B_frames = defaults().number<int>("skip_b_frames");
double ar_delta = defaults().number<double>("ar_delta");
int cut_on_ar_change = defaults().number<int>("cut_on_ar_change");
int padding = defaults().number<int>("padding");
int remove_before = defaults().number<int>("remove_before");
int remove_after = defaults().number<int>("remove_after");
int added_recording = defaults().number<int>("added_recording");
int delete_show_after_last_commercial = defaults().number<int>("delete_show_after_last_commercial");
int delete_show_before_first_commercial = defaults().number<int>("delete_show_before_first_commercial");
int delete_show_before_or_after_current = defaults().number<int>("delete_show_before_or_after_current");
int delete_block_after_commercial = defaults().number<int>("delete_block_after_commercial");
int min_commercial_break_at_start_or_end = defaults().number<int>("min_commercial_break_at_start_or_end");
int always_keep_first_seconds = defaults().number<int>("always_keep_first_seconds");
int always_keep_last_seconds = defaults().number<int>("always_keep_last_seconds");
bool intelligent_brightness = defaults().number<bool>("intelligent_brightness");
double black_percentile = defaults().number<double>("black_percentile");
double uniform_percentile = defaults().number<double>("uniform_percentile");
double score_percentile = defaults().number<double>("score_percentile");
double length_strict_modifier = defaults().number<double>("length_strict_modifier");
double length_nonstrict_modifier = defaults().number<double>("length_nonstrict_modifier");
double combined_length_strict_modifier = defaults().number<double>("combined_length_strict_modifier");
double combined_length_nonstrict_modifier = defaults().number<double>("combined_length_nonstrict_modifier");
double ar_wrong_modifier = defaults().number<double>("ar_wrong_modifier");
double ac_wrong_modifier = defaults().number<double>("ac_wrong_modifier");
double excessive_length_modifier = defaults().number<double>("excessive_length_modifier");
double dark_block_modifier = defaults().number<double>("dark_block_modifier");
double min_schange_modifier = defaults().number<double>("min_schange_modifier");
double max_schange_modifier = defaults().number<double>("max_schange_modifier");
double logo_present_modifier = defaults().number<double>("logo_present_modifier");
int punish_no_logo = defaults().number<int>("punish_no_logo");
int punish = defaults().number<int>("punish");
int reward = defaults().number<int>("reward");
double punish_threshold = defaults().number<double>("punish_threshold");
double punish_modifier = defaults().number<double>("punish_modifier");
double reward_modifier = defaults().number<double>("reward_modifier");
int border = defaults().number<int>("border");
int giveUpOnLogoSearch = defaults().number<int>("give_up_logo_search");
int delay_logo_search = defaults().number<int>("delay_logo_search");
double logo_max_percentage_of_screen = defaults().number<double>("logo_max_percentage_of_screen");
int ticker_tape = defaults().number<int>("ticker_tape");
int ticker_tape_percentage = defaults().number<int>("ticker_tape_percentage");
int top_ticker_tape = defaults().number<int>("top_ticker_tape");
int top_ticker_tape_percentage = defaults().number<int>("top_ticker_tape_percentage");
int ignore_side = defaults().number<int>("ignore_side");
int ignore_left_side = defaults().number<int>("ignore_left_side");
int ignore_right_side = defaults().number<int>("ignore_right_side");
int subtitles = defaults().number<int>("subtitles");
int logo_at_bottom = defaults().number<int>("logo_at_bottom");
int logo_at_side = defaults().number<int>("logo_at_side");
double logo_threshold = defaults().number<double>("logo_threshold");
double logo_percentage_threshold = defaults().number<double>("logo_percentage_threshold");
int logo_filter = defaults().number<int>("logo_filter");
int aggressive_logo_rejection = defaults().number<int>("aggressive_logo_rejection");
int edge_level_threshold = defaults().number<int>("edge_level_threshold");
int edge_radius = defaults().number<int>("edge_radius");
int edge_weight = defaults().number<int>("edge_weight");
int edge_step = defaults().number<int>("edge_step");
int num_logo_buffers = defaults().number<int>("num_logo_buffers");
bool useExistingLogoFile = defaults().number<bool>("use_existing_logo_file");
bool startOverAfterLogoInfoAvail = defaults().number<bool>("two_pass_logo");
bool connect_blocks_with_logo = defaults().number<bool>("connect_blocks_with_logo");
double logo_percentile = defaults().number<double>("logo_percentile");
double logo_fraction = defaults().number<double>("logo_fraction");
double shrink_logo = defaults().number<double>("shrink_logo");
int shrink_logo_tail = defaults().number<int>("shrink_logo_tail");
int before_logo = defaults().number<int>("before_logo");
int after_logo = defaults().number<int>("after_logo");
int where_logo = defaults().number<int>("where_logo");
unsigned int min_black_frames_for_break = defaults().number<unsigned int>("min_black_frames_for_break");
bool ccCheck = defaults().number<bool>("ccCheck");
double cc_commercial_type_modifier = defaults().number<double>("cc_commercial_type_modifier");
double cc_wrong_type_modifier = defaults().number<double>("cc_wrong_type_modifier");
double cc_correct_type_modifier = defaults().number<double>("cc_correct_type_modifier");
bool live_tv = defaults().number<bool>("live_tv");
int live_tv_retries = defaults().number<int>("live_tv_retries");
bool require_div5 = defaults().number<bool>("require_div5");
double div5_tolerance = defaults().number<double>("div5_tolerance");
int incommercial_frames = defaults().number<int>("incommercial_frames");
bool output_default = defaults().number<bool>("output_default");
bool output_chapters = defaults().number<bool>("output_chapters");
bool output_plist_cutlist = defaults().number<bool>("output_plist_cutlist");
bool output_zoomplayer_cutlist = defaults().number<bool>("output_zoomplayer_cutlist");
bool output_zoomplayer_chapter = defaults().number<bool>("output_zoomplayer_chapter");
bool output_scf = defaults().number<bool>("output_scf");
bool output_vcf = defaults().number<bool>("output_vcf");
bool output_vdr = defaults().number<bool>("output_vdr");
bool output_projectx = defaults().number<bool>("output_projectx");
bool output_avisynth = defaults().number<bool>("output_avisynth");
bool output_videoredo = defaults().number<bool>("output_videoredo");
bool output_videoredo3 = defaults().number<bool>("output_videoredo3");
int videoredo_offset = defaults().number<int>("videoredo_offset");
bool output_btv = defaults().number<bool>("output_btv");
bool output_edl = defaults().number<bool>("output_edl");
bool output_live = defaults().number<bool>("output_live");
int edl_offset = defaults().number<int>("edl_offset");
int timeline_repair = defaults().number<int>("timeline_repair");
int edl_skip_field = defaults().number<int>("edl_skip_field");
bool output_edlp = defaults().number<bool>("output_edlp");
bool output_bsplayer = defaults().number<bool>("output_bsplayer");
bool output_edlx = defaults().number<bool>("output_edlx");
bool output_cuttermaran = defaults().number<bool>("output_cuttermaran");
bool output_mpeg2schnitt = defaults().number<bool>("output_mpeg2schnitt");
bool output_womble = defaults().number<bool>("output_womble");
bool output_mls = defaults().number<bool>("output_mls");
bool output_mpgtx = defaults().number<bool>("output_mpgtx");
bool output_dvrmstb = defaults().number<bool>("output_dvrmstb");
bool output_dvrcut = defaults().number<bool>("output_dvrcut");
bool output_ipodchap = defaults().number<bool>("output_ipodchap");
bool output_framearray = defaults().number<bool>("output_framearray");
bool output_debugwindow = defaults().number<bool>("output_debugwindow");
bool output_tuning = defaults().number<bool>("output_tuning");
int output_training = defaults().number<int>("output_training");
bool output_false = defaults().number<bool>("output_false");
bool output_aspect = defaults().number<bool>("output_aspect");
bool output_demux = defaults().number<bool>("output_demux");
bool output_data = defaults().number<bool>("output_data");
bool output_srt = defaults().number<bool>("output_srt");
bool output_smi = defaults().number<bool>("output_smi");
bool output_timing = defaults().number<bool>("output_timing");
bool output_incommercial = defaults().number<bool>("output_incommercial");
bool output_ffmeta = defaults().number<bool>("output_ffmeta");
bool output_ffsplit = defaults().number<bool>("output_ffsplit");
bool deleteLogoFile = defaults().number<bool>("delete_logo_file");
int output_mkvtoolnix = defaults().number<int>("output_mkvtoolnix");
int cutsceneno = defaults().number<int>("cutscene_frame");
int cutscenedelta = defaults().number<int>("cutscene_threshold");
bool sage_framenumber_bug = defaults().number<bool>("sage_framenumber_bug");
bool sage_minute_bug = defaults().number<bool>("sage_minute_bug");
bool enable_mencoder_pts = defaults().number<bool>("enable_mencoder_pts");
char cutscenefile[1024]{};
char cutscenefile1[1024]{};
char cutscenefile2[1024]{};
char cutscenefile3[1024]{};
char cutscenefile4[1024]{};
char cutscenefile5[1024]{};
char cutscenefile6[1024]{};
char cutscenefile7[1024]{};
char cutscenefile8[1024]{};
char windowtitle[1024]{};
char cuttermaran_options[1024]{};
char mpeg2schnitt_options[1024]{};
char avisynth_options[1024]{};
char dvrcut_options[1024]{};

namespace {
template<std::size_t N> void copy_string(const comskip::config::Ini& ini, const char* key, char (&target)[N]) {
    const auto* value = ini.find(key);
    if (!value) return;
    if (value->size() >= N) throw std::invalid_argument(std::string(key) + " is too long");
    std::memcpy(target, value->c_str(), value->size() + 1);
}
struct InitializeStrings {
    InitializeStrings() {
        copy_string(defaults(), "cutscene_dumpfile", cutscenefile);
        copy_string(defaults(), "cutscenefile1", cutscenefile1);
        copy_string(defaults(), "cutscenefile2", cutscenefile2);
        copy_string(defaults(), "cutscenefile3", cutscenefile3);
        copy_string(defaults(), "cutscenefile4", cutscenefile4);
        copy_string(defaults(), "cutscenefile5", cutscenefile5);
        copy_string(defaults(), "cutscenefile6", cutscenefile6);
        copy_string(defaults(), "cutscenefile7", cutscenefile7);
        copy_string(defaults(), "cutscenefile8", cutscenefile8);
        copy_string(defaults(), "windowtitle", windowtitle);
        copy_string(defaults(), "cuttermaran_options", cuttermaran_options);
        copy_string(defaults(), "mpeg2schnitt_options", mpeg2schnitt_options);
        copy_string(defaults(), "avisynth_options", avisynth_options);
        copy_string(defaults(), "dvrcut_options", dvrcut_options);
    }
} initialize_strings;
}
namespace comskip::config {
void apply_settings(const Ini& ini) {
    if (const auto* language = ini.find("language"); language && *language != "en" && *language != "es")
        throw std::invalid_argument("Unsupported language: " + *language);
    auto profile = read_profile(ini, commercial_profile());
    std::vector<std::function<void()>> updates;
    auto number = [&]<class T>(const char* key, T& target, int sign = 1) {
        if (!ini.find(key)) return;
        T value = ini.number<T>(key);
        if ((std::string_view(key) == "thread_count" || std::string_view(key) == "num_logo_buffers" ||
             std::string_view(key) == "fps" || std::string_view(key) == "edge_radius" ||
             std::string_view(key) == "edge_step") && value <= 0)
            throw std::invalid_argument(std::string(key) + " must be positive");
        if (sign == -1) {
            if (value == std::numeric_limits<T>::lowest()) throw std::invalid_argument("Audio delay out of range");
            value = static_cast<T>(-value);
        }
        updates.emplace_back([&target, value] { target = value; });
    };
    auto text = [&]<std::size_t N>(const char* key, char (&target)[N]) {
        const auto* value = ini.find(key);
        if (!value) return;
        if (value->size() >= N) throw std::invalid_argument(std::string(key) + " is too long");
        if (std::string_view(key) == "windowtitle") {
            int placeholders = 0;
            for (std::size_t i = 0; i < value->size(); ++i) {
                if ((*value)[i] != '%') continue;
                if (++i == value->size() || ((*value)[i] != '%' && (*value)[i] != 's'))
                    throw std::invalid_argument("windowtitle accepts only %s and %%");
                if ((*value)[i] == 's' && ++placeholders > 1)
                    throw std::invalid_argument("windowtitle accepts at most one filename placeholder");
            }
        }
        updates.emplace_back([&target, value = *value] { std::memcpy(target, value.c_str(), value.size() + 1); });
    };
    number("detect_method", commDetectMethod);
    number("align_ac3_packets", ALIGN_AC3_PACKETS);
    number("verbose", verbose);
    number("max_brightness", max_brightness);
    number("maxbright", maxbright);
    number("test_brightness", test_brightness);
    number("max_avg_brightness", max_avg_brightness);
    number("max_commercialbreak", max_commercialbreak);
    number("min_commercialbreak", min_commercialbreak);
    number("max_commercial_size", max_commercial_size);
    number("min_commercial_size", min_commercial_size);
    number("min_show_segment_length", min_show_segment_length);
    number("max_volume", max_volume);
    number("max_silence", max_silence);
    number("non_uniformity", non_uniformity);
    number("min_silence", min_silence);
    number("remove_silent_segments", remove_silent_segments);
    number("noise_level", noise_level);
    number("brightness_jump", brightness_jump);
    number("fps", fps);
    number("validate_silence", validate_silence);
    number("validate_uniform", validate_uniform);
    number("validate_scenechange", validate_scenechange);
    number("global_threshold", global_threshold);
    number("disable_heuristics", disable_heuristics);
    number("cut_on_ac_change", cut_on_ac_change);
    number("thread_count", thread_count);
    number("hardware_decode", hardware_decode);
    number("play_nice_start", play_nice_start);
    number("play_nice_end", play_nice_end);
    number("play_nice_sleep", play_nice_sleep);
    number("max_repair_size", max_repair_size);
    number("ms_audio_delay", ms_audio_delay, -1);
    number("volume_slip", volume_slip);
    number("lowres", lowres);
    number("skip_b_frames", skip_B_frames);
    number("ar_delta", ar_delta);
    number("cut_on_ar_change", cut_on_ar_change);
    number("padding", padding);
    number("remove_before", remove_before);
    number("remove_after", remove_after);
    number("added_recording", added_recording);
    number("delete_show_after_last_commercial", delete_show_after_last_commercial);
    number("delete_show_before_first_commercial", delete_show_before_first_commercial);
    number("delete_show_before_or_after_current", delete_show_before_or_after_current);
    number("delete_block_after_commercial", delete_block_after_commercial);
    number("min_commercial_break_at_start_or_end", min_commercial_break_at_start_or_end);
    number("always_keep_first_seconds", always_keep_first_seconds);
    number("always_keep_last_seconds", always_keep_last_seconds);
    number("intelligent_brightness", intelligent_brightness);
    number("black_percentile", black_percentile);
    number("uniform_percentile", uniform_percentile);
    number("score_percentile", score_percentile);
    number("length_strict_modifier", length_strict_modifier);
    number("length_nonstrict_modifier", length_nonstrict_modifier);
    number("combined_length_strict_modifier", combined_length_strict_modifier);
    number("combined_length_nonstrict_modifier", combined_length_nonstrict_modifier);
    number("ar_wrong_modifier", ar_wrong_modifier);
    number("ac_wrong_modifier", ac_wrong_modifier);
    number("excessive_length_modifier", excessive_length_modifier);
    number("dark_block_modifier", dark_block_modifier);
    number("min_schange_modifier", min_schange_modifier);
    number("max_schange_modifier", max_schange_modifier);
    number("logo_present_modifier", logo_present_modifier);
    number("punish_no_logo", punish_no_logo);
    number("punish", punish);
    number("reward", reward);
    number("punish_threshold", punish_threshold);
    number("punish_modifier", punish_modifier);
    number("reward_modifier", reward_modifier);
    number("border", border);
    number("give_up_logo_search", giveUpOnLogoSearch);
    number("delay_logo_search", delay_logo_search);
    number("logo_max_percentage_of_screen", logo_max_percentage_of_screen);
    number("ticker_tape", ticker_tape);
    number("ticker_tape_percentage", ticker_tape_percentage);
    number("top_ticker_tape", top_ticker_tape);
    number("top_ticker_tape_percentage", top_ticker_tape_percentage);
    number("ignore_side", ignore_side);
    number("ignore_left_side", ignore_left_side);
    number("ignore_right_side", ignore_right_side);
    number("subtitles", subtitles);
    number("logo_at_bottom", logo_at_bottom);
    number("logo_at_side", logo_at_side);
    number("logo_threshold", logo_threshold);
    number("logo_percentage_threshold", logo_percentage_threshold);
    number("logo_filter", logo_filter);
    number("aggressive_logo_rejection", aggressive_logo_rejection);
    number("edge_level_threshold", edge_level_threshold);
    number("edge_radius", edge_radius);
    number("edge_weight", edge_weight);
    number("edge_step", edge_step);
    number("num_logo_buffers", num_logo_buffers);
    number("use_existing_logo_file", useExistingLogoFile);
    number("two_pass_logo", startOverAfterLogoInfoAvail);
    number("connect_blocks_with_logo", connect_blocks_with_logo);
    number("logo_percentile", logo_percentile);
    number("logo_fraction", logo_fraction);
    number("shrink_logo", shrink_logo);
    number("shrink_logo_tail", shrink_logo_tail);
    number("before_logo", before_logo);
    number("after_logo", after_logo);
    number("where_logo", where_logo);
    number("min_black_frames_for_break", min_black_frames_for_break);
    number("ccCheck", ccCheck);
    number("cc_commercial_type_modifier", cc_commercial_type_modifier);
    number("cc_wrong_type_modifier", cc_wrong_type_modifier);
    number("cc_correct_type_modifier", cc_correct_type_modifier);
    number("live_tv", live_tv);
    number("live_tv_retries", live_tv_retries);
    number("require_div5", require_div5);
    number("div5_tolerance", div5_tolerance);
    number("incommercial_frames", incommercial_frames);
    number("output_default", output_default);
    number("output_chapters", output_chapters);
    number("output_plist_cutlist", output_plist_cutlist);
    number("output_zoomplayer_cutlist", output_zoomplayer_cutlist);
    number("output_zoomplayer_chapter", output_zoomplayer_chapter);
    number("output_scf", output_scf);
    number("output_vcf", output_vcf);
    number("output_vdr", output_vdr);
    number("output_projectx", output_projectx);
    number("output_avisynth", output_avisynth);
    number("output_videoredo", output_videoredo);
    number("output_videoredo3", output_videoredo3);
    number("videoredo_offset", videoredo_offset);
    number("output_btv", output_btv);
    number("output_edl", output_edl);
    number("output_live", output_live);
    number("edl_offset", edl_offset);
    number("timeline_repair", timeline_repair);
    number("edl_skip_field", edl_skip_field);
    number("output_edlp", output_edlp);
    number("output_bsplayer", output_bsplayer);
    number("output_edlx", output_edlx);
    number("output_cuttermaran", output_cuttermaran);
    number("output_mpeg2schnitt", output_mpeg2schnitt);
    number("output_womble", output_womble);
    number("output_mls", output_mls);
    number("output_mpgtx", output_mpgtx);
    number("output_dvrmstb", output_dvrmstb);
    number("output_dvrcut", output_dvrcut);
    number("output_ipodchap", output_ipodchap);
    number("output_framearray", output_framearray);
    number("output_debugwindow", output_debugwindow);
    number("output_tuning", output_tuning);
    number("output_training", output_training);
    number("output_false", output_false);
    number("output_aspect", output_aspect);
    number("output_demux", output_demux);
    number("output_data", output_data);
    number("output_srt", output_srt);
    number("output_smi", output_smi);
    number("output_timing", output_timing);
    number("output_incommercial", output_incommercial);
    number("output_ffmeta", output_ffmeta);
    number("output_ffsplit", output_ffsplit);
    number("delete_logo_file", deleteLogoFile);
    number("output_mkvtoolnix", output_mkvtoolnix);
    number("cutscene_frame", cutsceneno);
    number("cutscene_threshold", cutscenedelta);
    number("sage_framenumber_bug", sage_framenumber_bug);
    number("sage_minute_bug", sage_minute_bug);
    number("enable_mencoder_pts", enable_mencoder_pts);
    text("cutscene_dumpfile", cutscenefile);
    text("cutscenefile1", cutscenefile1);
    text("cutscenefile2", cutscenefile2);
    text("cutscenefile3", cutscenefile3);
    text("cutscenefile4", cutscenefile4);
    text("cutscenefile5", cutscenefile5);
    text("cutscenefile6", cutscenefile6);
    text("cutscenefile7", cutscenefile7);
    text("cutscenefile8", cutscenefile8);
    text("windowtitle", windowtitle);
    text("cuttermaran_options", cuttermaran_options);
    text("mpeg2schnitt_options", mpeg2schnitt_options);
    text("avisynth_options", avisynth_options);
    text("dvrcut_options", dvrcut_options);
    for (const auto& update : updates) update();
    set_commercial_profile(std::move(profile));
}
}
