#pragma once
#include "settings_value.h"
#include <array>
#include <functional>
#include <tuple>
#include <utility>

namespace comskip::config::detail {
template<class T> struct SettingField {
    std::string_view key;
    T Settings::* member;
    int sign = 1;
};

inline constexpr auto setting_fields = std::tuple{
    std::array{
        SettingField<bool>{"align_ac3_packets", &Settings::ALIGN_AC3_PACKETS},
        SettingField<bool>{"intelligent_brightness", &Settings::intelligent_brightness},
        SettingField<bool>{"use_existing_logo_file", &Settings::useExistingLogoFile},
        SettingField<bool>{"two_pass_logo", &Settings::startOverAfterLogoInfoAvail},
        SettingField<bool>{"connect_blocks_with_logo", &Settings::connect_blocks_with_logo},
        SettingField<bool>{"ccCheck", &Settings::ccCheck},
        SettingField<bool>{"live_tv", &Settings::live_tv},
        SettingField<bool>{"require_div5", &Settings::require_div5},
        SettingField<bool>{"output_default", &Settings::output_default},
        SettingField<bool>{"output_chapters", &Settings::output_chapters},
        SettingField<bool>{"output_plist_cutlist", &Settings::output_plist_cutlist},
        SettingField<bool>{"output_zoomplayer_cutlist", &Settings::output_zoomplayer_cutlist},
        SettingField<bool>{"output_zoomplayer_chapter", &Settings::output_zoomplayer_chapter},
        SettingField<bool>{"output_scf", &Settings::output_scf},
        SettingField<bool>{"output_vcf", &Settings::output_vcf},
        SettingField<bool>{"output_vdr", &Settings::output_vdr},
        SettingField<bool>{"output_projectx", &Settings::output_projectx},
        SettingField<bool>{"output_avisynth", &Settings::output_avisynth},
        SettingField<bool>{"output_videoredo", &Settings::output_videoredo},
        SettingField<bool>{"output_videoredo3", &Settings::output_videoredo3},
        SettingField<bool>{"output_btv", &Settings::output_btv},
        SettingField<bool>{"output_edl", &Settings::output_edl},
        SettingField<bool>{"output_live", &Settings::output_live},
        SettingField<bool>{"output_edlp", &Settings::output_edlp},
        SettingField<bool>{"output_bsplayer", &Settings::output_bsplayer},
        SettingField<bool>{"output_edlx", &Settings::output_edlx},
        SettingField<bool>{"output_cuttermaran", &Settings::output_cuttermaran},
        SettingField<bool>{"output_mpeg2schnitt", &Settings::output_mpeg2schnitt},
        SettingField<bool>{"output_womble", &Settings::output_womble},
        SettingField<bool>{"output_mls", &Settings::output_mls},
        SettingField<bool>{"output_mpgtx", &Settings::output_mpgtx},
        SettingField<bool>{"output_dvrmstb", &Settings::output_dvrmstb},
        SettingField<bool>{"output_dvrcut", &Settings::output_dvrcut},
        SettingField<bool>{"output_ipodchap", &Settings::output_ipodchap},
        SettingField<bool>{"output_framearray", &Settings::output_framearray},
        SettingField<bool>{"output_debugwindow", &Settings::output_debugwindow},
        SettingField<bool>{"output_tuning", &Settings::output_tuning},
        SettingField<bool>{"output_false", &Settings::output_false},
        SettingField<bool>{"output_aspect", &Settings::output_aspect},
        SettingField<bool>{"output_demux", &Settings::output_demux},
        SettingField<bool>{"output_data", &Settings::output_data},
        SettingField<bool>{"output_srt", &Settings::output_srt},
        SettingField<bool>{"output_smi", &Settings::output_smi},
        SettingField<bool>{"output_timing", &Settings::output_timing},
        SettingField<bool>{"output_incommercial", &Settings::output_incommercial},
        SettingField<bool>{"output_ffmeta", &Settings::output_ffmeta},
        SettingField<bool>{"output_ffsplit", &Settings::output_ffsplit},
        SettingField<bool>{"delete_logo_file", &Settings::deleteLogoFile},
        SettingField<bool>{"sage_framenumber_bug", &Settings::sage_framenumber_bug},
        SettingField<bool>{"sage_minute_bug", &Settings::sage_minute_bug},
        SettingField<bool>{"enable_mencoder_pts", &Settings::enable_mencoder_pts}
    },
    std::array{
        SettingField<int>{"detect_method", &Settings::commDetectMethod},
        SettingField<int>{"verbose", &Settings::verbose},
        SettingField<int>{"max_brightness", &Settings::max_brightness},
        SettingField<int>{"maxbright", &Settings::maxbright},
        SettingField<int>{"test_brightness", &Settings::test_brightness},
        SettingField<int>{"max_avg_brightness", &Settings::max_avg_brightness},
        SettingField<int>{"max_volume", &Settings::max_volume},
        SettingField<int>{"max_silence", &Settings::max_silence},
        SettingField<int>{"non_uniformity", &Settings::non_uniformity},
        SettingField<int>{"min_silence", &Settings::min_silence},
        SettingField<int>{"remove_silent_segments", &Settings::remove_silent_segments},
        SettingField<int>{"noise_level", &Settings::noise_level},
        SettingField<int>{"brightness_jump", &Settings::brightness_jump},
        SettingField<int>{"validate_silence", &Settings::validate_silence},
        SettingField<int>{"validate_uniform", &Settings::validate_uniform},
        SettingField<int>{"validate_scenechange", &Settings::validate_scenechange},
        SettingField<int>{"disable_heuristics", &Settings::disable_heuristics},
        SettingField<int>{"cut_on_ac_change", &Settings::cut_on_ac_change},
        SettingField<int>{"thread_count", &Settings::thread_count},
        SettingField<int>{"hardware_decode", &Settings::hardware_decode},
        SettingField<int>{"play_nice_start", &Settings::play_nice_start},
        SettingField<int>{"play_nice_end", &Settings::play_nice_end},
        SettingField<int>{"max_repair_size", &Settings::max_repair_size},
        SettingField<int>{"ms_audio_delay", &Settings::ms_audio_delay, -1},
        SettingField<int>{"volume_slip", &Settings::volume_slip},
        SettingField<int>{"lowres", &Settings::lowres},
        SettingField<int>{"skip_b_frames", &Settings::skip_B_frames},
        SettingField<int>{"cut_on_ar_change", &Settings::cut_on_ar_change},
        SettingField<int>{"padding", &Settings::padding},
        SettingField<int>{"remove_before", &Settings::remove_before},
        SettingField<int>{"remove_after", &Settings::remove_after},
        SettingField<int>{"added_recording", &Settings::added_recording},
        SettingField<int>{"delete_show_after_last_commercial", &Settings::delete_show_after_last_commercial},
        SettingField<int>{"delete_show_before_first_commercial", &Settings::delete_show_before_first_commercial},
        SettingField<int>{"delete_show_before_or_after_current", &Settings::delete_show_before_or_after_current},
        SettingField<int>{"delete_block_after_commercial", &Settings::delete_block_after_commercial},
        SettingField<int>{"min_commercial_break_at_start_or_end", &Settings::min_commercial_break_at_start_or_end},
        SettingField<int>{"always_keep_first_seconds", &Settings::always_keep_first_seconds},
        SettingField<int>{"always_keep_last_seconds", &Settings::always_keep_last_seconds},
        SettingField<int>{"punish_no_logo", &Settings::punish_no_logo},
        SettingField<int>{"punish", &Settings::punish},
        SettingField<int>{"reward", &Settings::reward},
        SettingField<int>{"border", &Settings::border},
        SettingField<int>{"give_up_logo_search", &Settings::giveUpOnLogoSearch},
        SettingField<int>{"delay_logo_search", &Settings::delay_logo_search},
        SettingField<int>{"ticker_tape", &Settings::ticker_tape},
        SettingField<int>{"ticker_tape_percentage", &Settings::ticker_tape_percentage},
        SettingField<int>{"top_ticker_tape", &Settings::top_ticker_tape},
        SettingField<int>{"top_ticker_tape_percentage", &Settings::top_ticker_tape_percentage},
        SettingField<int>{"ignore_side", &Settings::ignore_side},
        SettingField<int>{"ignore_left_side", &Settings::ignore_left_side},
        SettingField<int>{"ignore_right_side", &Settings::ignore_right_side},
        SettingField<int>{"subtitles", &Settings::subtitles},
        SettingField<int>{"logo_at_bottom", &Settings::logo_at_bottom},
        SettingField<int>{"logo_at_side", &Settings::logo_at_side},
        SettingField<int>{"logo_filter", &Settings::logo_filter},
        SettingField<int>{"aggressive_logo_rejection", &Settings::aggressive_logo_rejection},
        SettingField<int>{"edge_level_threshold", &Settings::edge_level_threshold},
        SettingField<int>{"edge_radius", &Settings::edge_radius},
        SettingField<int>{"edge_weight", &Settings::edge_weight},
        SettingField<int>{"edge_step", &Settings::edge_step},
        SettingField<int>{"num_logo_buffers", &Settings::num_logo_buffers},
        SettingField<int>{"shrink_logo_tail", &Settings::shrink_logo_tail},
        SettingField<int>{"before_logo", &Settings::before_logo},
        SettingField<int>{"after_logo", &Settings::after_logo},
        SettingField<int>{"where_logo", &Settings::where_logo},
        SettingField<int>{"live_tv_retries", &Settings::live_tv_retries},
        SettingField<int>{"incommercial_frames", &Settings::incommercial_frames},
        SettingField<int>{"videoredo_offset", &Settings::videoredo_offset},
        SettingField<int>{"edl_offset", &Settings::edl_offset},
        SettingField<int>{"timeline_repair", &Settings::timeline_repair},
        SettingField<int>{"edl_skip_field", &Settings::edl_skip_field},
        SettingField<int>{"output_training", &Settings::output_training},
        SettingField<int>{"output_mkvtoolnix", &Settings::output_mkvtoolnix},
        SettingField<int>{"cutscene_frame", &Settings::cutsceneno},
        SettingField<int>{"cutscene_threshold", &Settings::cutscenedelta}
    },
    std::array{
        SettingField<double>{"max_commercialbreak", &Settings::max_commercialbreak},
        SettingField<double>{"min_commercialbreak", &Settings::min_commercialbreak},
        SettingField<double>{"max_commercial_size", &Settings::max_commercial_size},
        SettingField<double>{"min_commercial_size", &Settings::min_commercial_size},
        SettingField<double>{"min_show_segment_length", &Settings::min_show_segment_length},
        SettingField<double>{"fps", &Settings::fps},
        SettingField<double>{"global_threshold", &Settings::global_threshold},
        SettingField<double>{"ar_delta", &Settings::ar_delta},
        SettingField<double>{"black_percentile", &Settings::black_percentile},
        SettingField<double>{"uniform_percentile", &Settings::uniform_percentile},
        SettingField<double>{"score_percentile", &Settings::score_percentile},
        SettingField<double>{"length_strict_modifier", &Settings::length_strict_modifier},
        SettingField<double>{"length_nonstrict_modifier", &Settings::length_nonstrict_modifier},
        SettingField<double>{"combined_length_strict_modifier", &Settings::combined_length_strict_modifier},
        SettingField<double>{"combined_length_nonstrict_modifier", &Settings::combined_length_nonstrict_modifier},
        SettingField<double>{"ar_wrong_modifier", &Settings::ar_wrong_modifier},
        SettingField<double>{"ac_wrong_modifier", &Settings::ac_wrong_modifier},
        SettingField<double>{"excessive_length_modifier", &Settings::excessive_length_modifier},
        SettingField<double>{"dark_block_modifier", &Settings::dark_block_modifier},
        SettingField<double>{"min_schange_modifier", &Settings::min_schange_modifier},
        SettingField<double>{"max_schange_modifier", &Settings::max_schange_modifier},
        SettingField<double>{"logo_present_modifier", &Settings::logo_present_modifier},
        SettingField<double>{"punish_threshold", &Settings::punish_threshold},
        SettingField<double>{"punish_modifier", &Settings::punish_modifier},
        SettingField<double>{"reward_modifier", &Settings::reward_modifier},
        SettingField<double>{"logo_max_percentage_of_screen", &Settings::logo_max_percentage_of_screen},
        SettingField<double>{"logo_threshold", &Settings::logo_threshold},
        SettingField<double>{"logo_percentage_threshold", &Settings::logo_percentage_threshold},
        SettingField<double>{"logo_percentile", &Settings::logo_percentile},
        SettingField<double>{"logo_fraction", &Settings::logo_fraction},
        SettingField<double>{"shrink_logo", &Settings::shrink_logo},
        SettingField<double>{"cc_commercial_type_modifier", &Settings::cc_commercial_type_modifier},
        SettingField<double>{"cc_wrong_type_modifier", &Settings::cc_wrong_type_modifier},
        SettingField<double>{"cc_correct_type_modifier", &Settings::cc_correct_type_modifier},
        SettingField<double>{"div5_tolerance", &Settings::div5_tolerance}
    },
    std::array{
        SettingField<long>{"play_nice_sleep", &Settings::play_nice_sleep}
    },
    std::array{
        SettingField<unsigned int>{"min_black_frames_for_break", &Settings::min_black_frames_for_break}
    },
    std::array{
        SettingField<std::string>{"cutscene_dumpfile", &Settings::cutscenefile},
        SettingField<std::string>{"cutscenefile1", &Settings::cutscenefile1},
        SettingField<std::string>{"cutscenefile2", &Settings::cutscenefile2},
        SettingField<std::string>{"cutscenefile3", &Settings::cutscenefile3},
        SettingField<std::string>{"cutscenefile4", &Settings::cutscenefile4},
        SettingField<std::string>{"cutscenefile5", &Settings::cutscenefile5},
        SettingField<std::string>{"cutscenefile6", &Settings::cutscenefile6},
        SettingField<std::string>{"cutscenefile7", &Settings::cutscenefile7},
        SettingField<std::string>{"cutscenefile8", &Settings::cutscenefile8},
        SettingField<std::string>{"windowtitle", &Settings::windowtitle},
        SettingField<std::string>{"cuttermaran_options", &Settings::cuttermaran_options},
        SettingField<std::string>{"mpeg2schnitt_options", &Settings::mpeg2schnitt_options},
        SettingField<std::string>{"avisynth_options", &Settings::avisynth_options},
        SettingField<std::string>{"dvrcut_options", &Settings::dvrcut_options},
        SettingField<std::string>{"language", &Settings::language},
        SettingField<std::string>{"locale_directory", &Settings::locale_directory}
    },
};

// One descriptor schema serves pure loading and the temporary legacy bridge.
template<class S, class Visitor> void for_each_setting(S& settings, Visitor&& visitor) {
    std::apply([&](const auto&... group) {
        ([&] {
            for (const auto& field : group)
                std::invoke(visitor, field.key, settings.*(field.member), field.sign);
        }(), ...);
    }, setting_fields);
}
}
