if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "embed_font requires INPUT and OUTPUT")
endif()
file(READ "${INPUT}" font_hex HEX)
file(SIZE "${INPUT}" font_size)
if(font_size GREATER 2147483647 OR font_size EQUAL 0)
    message(FATAL_ERROR "Bundled font must fit the SDL read-only stream length")
endif()
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," font_bytes "${font_hex}")
file(WRITE "${OUTPUT}" "// Generated from NotoSans.ttf; distributed under assets/fonts/OFL.txt.\n#include \"bundled_font.h\"\nnamespace comskip::ui {\nnamespace {\nconst unsigned char font_bytes[] = {${font_bytes}};\n}\nstd::span<const unsigned char> bundled_font() noexcept { return font_bytes; }\n}\n")
